<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><%= U::htmlize(pageTemplate["title"]) %></title>
    <link rel="stylesheet" href="/css/styles.css" type="text/css"/>
    <link rel="icon" href="/images/favicon.ico">
  </head>
  <body lang="en">
    <header>
      <div class="headercontainer">
        <div class="header">
		  <h1>REMOTE <%= U::htmlize(pageTemplate["title"]) %></h1>
        </div>
      </div>
    </header>
    <div class="contentcontainer">
      <div class="content">
